[package]
name = "trng"
version = "0.1.0"
edition = "2021"
authors = ["Lukas Pfeifer"]
description = "The TRNG interpreter playground."
keywords = ["trng", "brainfuck", "turing"]

[dependencies]
tui = "0.19"
crossterm = "0.25"
libtrng = { path = "../libtrng" }